#!/bin/bash
hostname ceph-osd03

#host file
rm -rf /etc/hosts
cp /opt/openstack-working/hosts /etc/hosts
chmod a-wx /etc/hosts

#interface
rm -rf /etc/network/interfaces
cp /opt/openstack-working/interfaces/cephosd3/interfaces /etc/network
ifup eth1

