#!/bin/bash
hostname swift-proxy01

#host file
rm -rf /etc/hosts
cp /opt/openstack-working/hosts /etc/hosts

#interface
rm -rf /etc/network/interfaces
cp /opt/openstack-working/interfaces/swiftproxy/interfaces /etc/network
ifup eth1

